### ISSUE TITLE
Написать комментарии к PHP классам и методам + залить документацию

### ISSUE THREAD

**Issue by Dima2002iq** [moad-dev/otzyvus#127]
Прописать комментарии к ***каждому самодельному классу*** и методу php в проекте. С помощью следующей документации [phpDocumentator](https://docs.phpdoc.org/latest/guide/references/phpdoc/basic-syntax.html).

**Comment by nizamovtimur** [comment]
залейте в папку docs ещё и картинку с архитектурой (я че, зря рисовал её?)

**Comment by daniil7** [comment]
Остались комменты к сервисам:

- Electives
- Search

+ залить картинку с архитектурой
